### ISSUE TITLE
如果在执行类似 tsc -w语句后如何能继续执行后面的语句

### ISSUE THREAD

**Issue by newitp** [CraftsDeveloper/Speaker#8]
### `child_process.execSync` 执行`webpack-dev-server`或者 `tsc -w` 命令后，不能继续往下执行了

- 在使用node 执行如下index.js时，发现后一句的打印语句没有执行
```
const { execSync } = require('child_process');

execSync("tsc -w");

console.log( ' after tsc -w ' )
```

- 在使用webpack-dev-server启动本地服务时，也有这个问题

```
const { execSync } = require('child_process');

execSync("webpack-dev-server --config webpack.config.js");

console.log( ' after webpack-dev-serve' )
```
- 在package.json中的script语句中，也是如此，在`tsc -w` 后 再跟一条语句，比如 
`tsc -w && npm start`  后面的 `npm start `也不会执行

**Comment by Jokcy** [comment]
因为像`webpack-dev-server --config webpack.config.js`这样的命令是长期运行的，并不会返回，而你使用的是`execSync`也就是同步执行，对于一个不会返回的命令相当于你的`execSync`没有结束，当然不会继续向下执行。

**Comment by wshuhd** [comment]
@Jokcy 谢谢明白了，然后我也找到办法了，_ concurrently 应该可以同时执行多条‘不返回的’命令
